import type { Project } from '~/types/project';

// Helper function to generate a random ID
const generateId = (): string => {
  return Math.random().toString(36).substring(2, 15);
};

// Mock data for blockchain projects
export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'DeFiPulse',
    description: 'Automated liquidity provision and yield farming aggregator with AI-driven strategy optimization',
    token: {
      symbol: 'PULSE',
      name: 'DeFiPulse',
      marketCap: 142000000,
      priceChangePercentage24h: 8.45,
      currentPrice: 3.78,
      icon: 'https://images.pexels.com/photos/844124/pexels-photo-844124.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'DeFi',
    riskLevel: 'Medium',
    launchDate: new Date('2023-08-15'),
    website: 'https://defipulse.example.com',
    isHot: true,
  },
  {
    id: generateId(),
    title: 'MetaRealms',
    description: 'Immersive metaverse platform with integrated NFT marketplace and virtual land ownership',
    token: {
      symbol: 'REALM',
      name: 'MetaRealms',
      marketCap: 89000000,
      priceChangePercentage24h: -4.2,
      currentPrice: 1.15,
      icon: 'https://images.pexels.com/photos/2882634/pexels-photo-2882634.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'NFT',
    riskLevel: 'High',
    launchDate: new Date('2023-05-22'),
    website: 'https://metarealms.example.com',
  },
  {
    id: generateId(),
    title: 'CryptoQuest',
    description: 'Play-to-earn RPG with decentralized item ownership and cross-game asset portability',
    token: {
      symbol: 'QUEST',
      name: 'CryptoQuest',
      marketCap: 67500000,
      priceChangePercentage24h: 12.8,
      currentPrice: 0.85,
      icon: 'https://images.pexels.com/photos/1314543/pexels-photo-1314543.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'GameFi',
    riskLevel: 'Medium',
    website: 'https://cryptoquest.example.com',
    isHot: true,
  },
  {
    id: generateId(),
    title: 'ZeroChain',
    description: 'High-throughput Layer 1 blockchain with zero-knowledge proof privacy and quantum resistance',
    token: {
      symbol: 'ZERO',
      name: 'ZeroChain',
      marketCap: 325000000,
      priceChangePercentage24h: -1.5,
      currentPrice: 5.32,
      icon: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'Layer1',
    riskLevel: 'Low',
    launchDate: new Date('2022-11-30'),
    website: 'https://zerochain.example.com',
  },
  {
    id: generateId(),
    title: 'DataDAO',
    description: 'Decentralized governance platform for managing and monetizing shared data assets',
    token: {
      symbol: 'DATA',
      name: 'DataDAO',
      marketCap: 45000000,
      priceChangePercentage24h: 6.7,
      currentPrice: 0.42,
      icon: 'https://images.pexels.com/photos/669996/pexels-photo-669996.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'DAO',
    riskLevel: 'High',
    website: 'https://datadao.example.com',
  },
  {
    id: generateId(),
    title: 'ScaleSphere',
    description: 'Layer 2 scaling solution with ZK-rollup technology for Ethereum applications',
    token: {
      symbol: 'SCALE',
      name: 'ScaleSphere',
      marketCap: 178000000,
      priceChangePercentage24h: 3.2,
      currentPrice: 2.15,
      icon: 'https://images.pexels.com/photos/8451490/pexels-photo-8451490.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'Layer2',
    riskLevel: 'Medium',
    launchDate: new Date('2023-02-10'),
    website: 'https://scalesphere.example.com',
  },
  {
    id: generateId(),
    title: 'PrivacyShield',
    description: 'Privacy-focused cross-chain bridge with confidential transaction capabilities',
    token: {
      symbol: 'SHIELD',
      name: 'PrivacyShield',
      marketCap: 92000000,
      priceChangePercentage24h: -2.8,
      currentPrice: 1.65,
      icon: 'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'Privacy',
    riskLevel: 'High',
    website: 'https://privacyshield.example.com',
  },
  {
    id: generateId(),
    title: 'ChainOracle',
    description: 'Decentralized oracle network for secure real-world data feeds with cryptographic verification',
    token: {
      symbol: 'ORACLE',
      name: 'ChainOracle',
      marketCap: 215000000,
      priceChangePercentage24h: 5.4,
      currentPrice: 4.27,
      icon: 'https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'Infrastructure',
    riskLevel: 'Low',
    launchDate: new Date('2022-09-05'),
    website: 'https://chainoracle.example.com',
    isHot: true,
  },
  {
    id: generateId(),
    title: 'TokenVerse',
    description: 'Social token platform enabling creators to launch personalized economies',
    token: {
      symbol: 'VERSE',
      name: 'TokenVerse',
      marketCap: 53000000,
      priceChangePercentage24h: -6.2,
      currentPrice: 0.75,
      icon: 'https://images.pexels.com/photos/7788009/pexels-photo-7788009.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    category: 'DeFi',
    riskLevel: 'Extreme',
    website: 'https://tokenverse.example.com',
  },
];
